Item:
  Type: PAPER
  Name: "&c&lToken Note"
  Lore: 
    - ""
    - "&fWorth: [AMOUNT_COMMAS]"
    - "&fWithdrawer: [WITHDRAWER]"
  ItemData: 0
  Encanted: false
  #Item type must be in all caps
  #ItemData should be a number from this list: https://minecraftitemids.com/types/dye
  #Placeholders:
  #[WITHDRAWER] - The person who withdrew the TokenNote
  #[AMOUNT] - The amount, no commas
  #[AMOUNT_COMMAS] - Amount, formatted with commas
General:
  Stacakble: false
  WithdrawSyntax: "&cUsage: /tokenwithdraw (amount)"
  WithdrawPermission: "withdraw.perm"
  WithdrawPermissionMessage: "&cYou don't have permission to do this!"
  ConsoleMessage: "&cYou must be a player to execute this command!"
  NotEnoughTokensMessage: "&cYou don't have enough tokens to do this!"
  CompletedMsg: "&cWithdrew!"
  CannotBeNegativeMsg: "&cYou can't create a negative banknote!"
  #Completed message supports the 3 placeholders mentioned above
  AddedBalanceMsg: "&cAdded [AMOUNT_COMMAS] tokens to your balance!"
  #Message to send when tokens are added to a player's balance, supports [AMOUNT] and [AMOUNT_COMMAS]